stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t myapp .

test:
  stage: test
  script:
    - docker run myapp npm test

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker tag myapp registry.gitlab.com/myuser/myproject:latest
    - docker push registry.gitlab.com/myuser/myproject:latest
