#version: '3'
services:
  backend:
    image: tharushi104/backend
    ports:
      - "5001:5001"
    env_file:
      - .env 

  frontend:
    image: tharushi104/frontend
    ports:
      - "8081:80" 
