#version: '3'
#services:
 # backend:
    #image: tharushi104/backend
    #build: ./backend
    #ports:
    #  - "5001:5001"
    #env_file:
     # - ./backend/.env

  #frontend:
    #image: tharushi104/frontend
    #ports:
    #  - "8081:80" 

version: '3'
services:
  backend:
    build:
      context: ./backend  # Path to the backend directory
    ports:
      - "5001:5001"
    env_file:
      - backend/.env  # Make sure this points to the correct location of the .env file

  frontend:
    image: tharushi104/frontend
    ports:
      - "8081:80"
