#version: '3'
#services:
 # backend:
    #image: tharushi104/backend
    #build: ./backend
    #ports:
    #  - "5001:5001"
    #env_file:
     # - ./backend/.env

  #frontend:
    #image: tharushi104/frontend
    #ports:
    #  - "8081:80" 


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5001:5001"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8081:80"
